version: '3.8'

services:
  app:
    image: danielrrsilva/idea-java-app:V7
    container_name: app_container
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ideadb
      DB_USER: root
      DB_PASSWORD: urubu100
      CODIGOTOTEM: ${CODIGOTOTEM}
    networks:
      - app-network

  db:
    image: danielrrsilva/idea-data-base:V2
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
      MYSQL_DATABASE: ideadb
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge